# aop注解
server:
  #端口
  port: 9803
spring:
  datasource:
    url: jdbc:mysql://192.168.157.128:3306/testDB?useUnicode=yes&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&useSSL=false
    username: root
    password: anbswdc123
  application:
    #当前服务名称
    name: test
mybatis:
  #对应实体类路径
  type-aliases-package: com.pro.eneity
  #对应mapper映射文件路径
  mapper-locations: classpath:mapper/*.xml

